@server = http://localhost:4004
@service = /admin
@username = alice
@password = 1234


#############################################
#                BOOKS                      #
#############################################

### GET all books
GET {{server}}{{service}}/Books
Authorization: Basic {{username}}:{{password}}


### GET book by ID
GET {{server}}{{service}}/Books(ID='1538245a-f620-426b-b4b3-f2242ae594cf')
Authorization: Basic {{username}}:{{password}}


### FILTER: books where genre = Fiction (0)
GET {{server}}{{service}}/Books?$filter=genre eq 0
Authorization: Basic {{username}}:{{password}}


### CREATE book //CANNOT CREATE NOW I PROTECTED THE FUNCTIONALITY
POST {{server}}{{service}}/Books
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "title": "The Last Kingdom",
  "genre": 1
}


### UPDATE (PATCH) a book
PATCH {{server}}{{service}}/Books(ID='PUT-BOOK-ID')
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "title": "Updated Title"
}


### REPLACE (PUT) a book
PUT {{server}}{{service}}/Books(ID='PUT-BOOK-ID')
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "ID": "PUT-BOOK-ID",
  "title": "Replaced Book Object",
  "genre": 0
}


### DELETE a book
DELETE {{server}}{{service}}/Books(ID='PUT-BOOK-ID')
Authorization: Basic {{username}}:{{password}}


#################################################
#                AUTHORS                        #
#################################################

### GET all authors
GET {{server}}{{service}}/Authors
Authorization: Basic {{username}}:{{password}}





### CREATE author
POST {{server}}{{service}}/Authors
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "name": "New Author"
}


### DELETE author
DELETE {{server}}{{service}}/Authors(ID='a1f1b002-2222-4df0-baaa-aa2222222222')
Authorization: Basic {{username}}:{{password}}



### GET all BookAuthors
GET {{server}}{{service}}/BookAuthors
Authorization: Basic {{username}}:{{password}}


### FILTER: all books linked to one author
GET {{server}}{{service}}/BookAuthors?author_ID='a1f1b002-2222-4df0-baaa-aa2222222222'
Authorization: Basic {{username}}:{{password}}




